"""create warframe table

Revision ID: c42132c20817
Revises: dc808e1eb3ad
Create Date: 2025-10-22 11:05:26.412708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42132c20817'
down_revision: Union[str, Sequence[str], None] = 'dc808e1eb3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warframes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_name', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('health', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('shield', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('armor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('power', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('sprint_speed', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('mastery_rank', sa.Integer(), nullable=False),
    sa.Column('polarities', sa.JSON(), nullable=True),
    sa.Column('aura_polarity', sa.String(length=20), nullable=False),
    sa.Column('exilus_polarity', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warframes')
    # ### end Alembic commands ###
